const f=(key,label,type="text",options=null)=>({key,label,type,options});

export const navGroups=[
  ["Visão geral",[["dashboard","Visão geral"]]],
  ["Operação",[["orders","Pedidos"],["delivery_jobs","Entregas"],["support","Suporte"],["documents","Aprovações"],["enforcements","Suspensões e bloqueios"]]],
  ["Cadastros",[["states","Estados"],["fairs","Feiras"],["users","Usuários"],["vendors","Feirantes"],["drivers","Entregadores"],["products","Produtos"],["categories","Categorias"],["regions","Regiões"]]],
  ["Regras do negócio",[["vehicle_rules","Veículos"],["delivery_fees","Frete"],["platform_fees","Taxas"],["payment_methods","Pagamentos"],["cancellation_reasons","Cancelamentos"],["onboarding_requirements","Documentos exigidos"]]],
  ["Comercial e financeiro",[["promotions","Promoções"],["payouts","Repasses"],["reviews","Avaliações"]]],
  ["Comunicação",[["content","Conteúdo"],["announcements","Avisos"],["notifications","Mensagens"]]],
  ["Sistema",[["settings","Configurações"],["features","Recursos"],["integrations","Integrações"],["privacy","LGPD"],["permissions","Permissões"],["audit","Auditoria"]]]
];

const roles=["customer","vendor","delivery","admin","fair_manager"];
const orderStatus=["pending_payment","paid","accepted","preparing","ready_for_pickup","driver_assigned","collected","out_for_delivery","delivered","canceled","refunded"];
const docStatus=["pending","under_review","approved","correction_required","rejected"];
const payoutStatus=["pending","available","requested","paid","failed"];
const permissionOptions=[
  "*",
  "operations.manage",
  "documents.review",
  "accounts.enforce",
  "registrations.manage",
  "rules.manage",
  "finance.manage",
  "communications.manage",
  "settings.manage",
  "permissions.manage",
  "audit.view"
];

export const modules={
  fairs:{label:"Feiras",table:"fairs",desc:"Ative, pause e edite as feiras exibidas no Feiraê.",create:true,cols:["name","address","is_active","opening_hours"],fields:[f("name","Nome"),f("description","Descrição","textarea"),f("address","Endereço"),f("is_active","Ativa","checkbox"),f("opening_hours","Horários","json")]},
  users:{label:"Usuários",table:"profiles",desc:"Perfis, papéis e acesso. Use as ações para suspender ou banir uma conta.",create:false,del:false,audit:true,enforcementTarget:true,cols:["id","full_name","phone","role","created_at"],fields:[f("full_name","Nome"),f("phone","Telefone"),f("role","Papel","select",roles)]},
  vendors:{label:"Feirantes",table:"vendor_profiles",desc:"Aprovação e dados operacionais dos feirantes. Suspensões ficam registradas sem apagar o cadastro.",create:false,del:false,audit:true,enforcementTarget:true,cols:["id","business_name","approved","description","created_at"],fields:[f("business_name","Nome da banca"),f("description","Descrição","textarea"),f("approved","Aprovado","checkbox")]},
  drivers:{label:"Entregadores",table:"delivery_profiles",desc:"Aprovação e dados operacionais do entregador. Você pode suspender, bloquear entregas ou banir sem excluir o histórico.",create:false,del:false,audit:true,enforcementTarget:true,cols:["id","approved","city","state","receiving_method","updated_at"],fields:[f("approved","Aprovado","checkbox"),f("city","Cidade"),f("state","UF"),f("receiving_method","Forma de recebimento")]},
  documents:{label:"Aprovações",table:"onboarding_documents",desc:"Abra o arquivo enviado, revise validade, aprove, rejeite ou solicite correção.",create:false,del:false,audit:true,documentViewer:true,cols:["profile_id","document_type","file_path","status","expires_at","correction_reason","updated_at"],fields:[f("status","Status","select",docStatus),f("expires_at","Validade","date"),f("correction_reason","Motivo da correção","textarea")]},
  products:{label:"Produtos",table:"products",desc:"Catálogo consolidado; a gestão pode corrigir ou pausar.",create:false,del:false,audit:true,cols:["name","price","promotion_price","stock","unit","available"],fields:[f("name","Produto"),f("price","Preço","number"),f("promotion_price","Preço promocional","number"),f("stock","Estoque","number"),f("unit","Unidade"),f("available","Disponível","checkbox")]},
  categories:{label:"Categorias",table:"categories",desc:"Categorias usadas no catálogo.",create:true,del:false,cols:["name","active"],fields:[f("name","Nome"),f("active","Ativa","checkbox")]},
  states:{label:"Estados",table:"service_states",key:"code",desc:"Controle em quais estados o Feiraê está ativo e quais operações ficam liberadas.",create:true,del:false,cols:["code","name","customer_orders_enabled","vendor_registration_enabled","delivery_enabled","active","sort_order"],fields:[f("code","UF"),f("name","Estado"),f("customer_orders_enabled","Pedidos","checkbox"),f("vendor_registration_enabled","Cadastro feirante","checkbox"),f("delivery_enabled","Entregas","checkbox"),f("active","Ativo","checkbox"),f("sort_order","Ordem","number")]},
  regions:{label:"Regiões",table:"service_regions",desc:"Onde clientes, feirantes e entregadores podem operar.",create:true,cols:["name","state","city","default_radius_km","customer_orders_enabled","vendor_registration_enabled","delivery_enabled","active"],fields:[f("code","Código"),f("name","Nome"),f("state","UF"),f("city","Cidade"),f("default_radius_km","Raio padrão km","number"),f("customer_orders_enabled","Pedidos","checkbox"),f("vendor_registration_enabled","Cadastro feirante","checkbox"),f("delivery_enabled","Entregas","checkbox"),f("active","Ativa","checkbox"),f("sort_order","Ordem","number")]},
  vehicle_rules:{label:"Veículos permitidos",table:"vehicle_type_rules",desc:"Catálogo global de modalidades permitidas no Feiraê. Adicione, ative/desative e defina o peso máximo de cada tipo; não edita o veículo particular do entregador.",create:true,cols:["display_name","default_capacity_kg","requires_plate","requires_vehicle_document","requires_cnh","active"],fields:[f("code","Código"),f("display_name","Nome do tipo"),f("default_capacity_kg","Peso máximo (kg)","number"),f("requires_plate","Exige placa","checkbox"),f("requires_vehicle_document","Exige documento","checkbox"),f("requires_cnh","Exige CNH","checkbox"),f("active","Ativo","checkbox"),f("sort_order","Ordem","number")]},
  delivery_fees:{label:"Frete",table:"delivery_fee_rules",desc:"Fórmula por distância, tempo, peso, região e veículo.",create:true,cols:["name","active","priority","base_fee","per_km","per_minute","per_kg","minimum_charge","minimum_driver_payout"],fields:[f("name","Regra"),f("active","Ativa","checkbox"),f("priority","Prioridade","number"),f("region_id","Região UUID"),f("vehicle_code","Código veículo"),f("base_fee","Base","number"),f("per_km","Por km","number"),f("per_minute","Por minuto","number"),f("per_kg","Por kg","number"),f("minimum_charge","Cobrança mínima","number"),f("maximum_charge","Cobrança máxima","number"),f("minimum_driver_payout","Mínimo entregador","number"),f("platform_fee_percent","Taxa plataforma %","number"),f("max_distance_km","Distância máxima km","number"),f("starts_at","Início","datetime"),f("ends_at","Fim","datetime")]},
  platform_fees:{label:"Taxas",table:"platform_fee_rules",desc:"Taxas administrativas por pedido, banca, entrega ou pagamento.",create:true,cols:["name","scope","percentage","fixed_amount","active","priority"],fields:[f("name","Nome"),f("scope","Escopo","select",["order","vendor","delivery","payment"]),f("percentage","Percentual","number"),f("fixed_amount","Valor fixo","number"),f("active","Ativa","checkbox"),f("priority","Prioridade","number"),f("starts_at","Início","datetime"),f("ends_at","Fim","datetime")]},
  payment_methods:{label:"Pagamentos",table:"payment_method_rules",desc:"Pix, cartões, carteira e pagamento na entrega.",create:true,cols:["label","method_type","active","customer_enabled","vendor_enabled","delivery_enabled","requires_online_provider"],fields:[f("code","Código"),f("label","Nome"),f("method_type","Tipo","select",["pix","credit_card","debit_card","cash","card_on_delivery","wallet","other"]),f("active","Ativo","checkbox"),f("customer_enabled","Cliente","checkbox"),f("vendor_enabled","Feirante","checkbox"),f("delivery_enabled","Entregador","checkbox"),f("requires_online_provider","Exige provedor","checkbox"),f("sort_order","Ordem","number")]},
  cancellation_reasons:{label:"Cancelamentos",table:"cancellation_reasons",desc:"Motivos, etapas, detalhes, suporte e penalidades.",create:true,cols:["label","actor_role","flow_stage","requires_details","opens_support_ticket","penalty_amount","active"],fields:[f("code","Código"),f("actor_role","Papel","select",["customer","vendor","delivery","admin"]),f("flow_stage","Etapa"),f("label","Motivo"),f("requires_details","Exige descrição","checkbox"),f("opens_support_ticket","Abre suporte","checkbox"),f("penalty_amount","Penalidade","number"),f("active","Ativo","checkbox"),f("sort_order","Ordem","number")]},
  onboarding_requirements:{label:"Documentos exigidos",table:"onboarding_requirements",desc:"Exigências por papel e tipo de veículo.",create:true,cols:["profile_role","label","document_type","vehicle_type","required","critical","expiration_required","active"],fields:[f("profile_role","Papel","select",["vendor","delivery"]),f("document_type","Código"),f("vehicle_type","Tipo veículo"),f("label","Nome"),f("required","Obrigatório","checkbox"),f("critical","Crítico","checkbox"),f("expiration_required","Exige validade","checkbox"),f("instructions","Instruções","textarea"),f("active","Ativo","checkbox"),f("sort_order","Ordem","number")]},
  orders:{label:"Pedidos",table:"orders",desc:"Acompanhe pedidos e intervenha quando necessário.",create:false,del:false,audit:true,cols:["id","status","payment_status","subtotal","delivery_fee","total","created_at"],fields:[f("status","Status","select",orderStatus),f("payment_status","Status pagamento")]},
  delivery_jobs:{label:"Entregas",table:"deliveries",desc:"Corridas, entregador atribuído, taxa e ocorrências.",create:false,del:false,audit:true,cols:["order_id","delivery_id","status","fee","cancel_reason","accepted_at","delivered_at"],fields:[f("delivery_id","Entregador UUID"),f("status","Status"),f("fee","Valor","number"),f("cancel_reason","Motivo","textarea")]},
  support:{label:"Suporte",table:"support_tickets",desc:"Ocorrências ligadas a pedidos e usuários.",create:false,del:false,audit:true,cols:["order_id","actor_role","topic","priority","status","created_at"],fields:[f("priority","Prioridade","select",["normal","urgent"]),f("status","Status","select",["open","resolved","closed"]),f("details","Detalhes","textarea")]},
  enforcements:{label:"Suspensões e bloqueios",table:"account_enforcements",desc:"Histórico de suspensões, banimentos e bloqueios. Não apague punições: revogue para manter auditoria.",create:true,del:false,cols:["profile_id","action_type","status","reason","starts_at","ends_at","created_at"],fields:[f("profile_id","Usuário UUID"),f("action_type","Ação","select",["suspension","ban","orders_block","sales_block","deliveries_block"]),f("status","Status","select",["active","revoked","expired"]),f("reason","Motivo","textarea"),f("starts_at","Início","datetime"),f("ends_at","Até","datetime")]},
  promotions:{label:"Promoções",table:"promotions",desc:"Campanhas e regras promocionais das bancas.",create:false,del:false,audit:true,cols:["name","promotion_type","discount_value","minimum_order","vendor_pays_delivery","active","starts_at","ends_at"],fields:[f("name","Nome"),f("discount_value","Desconto","number"),f("minimum_order","Pedido mínimo","number"),f("vendor_pays_delivery","Feirante paga frete","checkbox"),f("active","Ativa","checkbox"),f("starts_at","Início","datetime"),f("ends_at","Fim","datetime")]},
  payouts:{label:"Repasses",table:"payouts",desc:"Valores pendentes, disponíveis, solicitados e pagos.",create:false,del:false,audit:true,cols:["profile_id","role","amount","status","provider_reference","requested_at","paid_at","created_at"],fields:[f("status","Status","select",payoutStatus),f("provider_reference","Referência provedor")]},
  reviews:{label:"Avaliações",table:"order_reviews",desc:"Moderação das avaliações vinculadas aos pedidos.",create:false,del:false,audit:true,cols:["order_id","author_role","target_role","rating","comment","visible","created_at"],fields:[f("visible","Visível","checkbox"),f("moderation_reason","Motivo moderação","textarea")]},
  features:{label:"Recursos",table:"feature_flags",key:"key",desc:"Ligue ou desligue recursos sem novo deploy.",create:true,cols:["key","label","enabled","public_readable","description","updated_at"],fields:[f("key","Chave"),f("label","Nome"),f("enabled","Ativo","checkbox"),f("public_readable","Público","checkbox"),f("description","Descrição","textarea")]},
  content:{label:"Conteúdo",table:"content_blocks",key:"key",desc:"Banners, textos, chamadas e conteúdo institucional.",create:true,cols:["key","area","title","active","starts_at","ends_at"],fields:[f("key","Chave"),f("area","Área"),f("title","Título"),f("body","Texto","textarea"),f("media_url","Imagem URL"),f("action_label","Texto botão"),f("action_url","Destino"),f("active","Ativo","checkbox"),f("starts_at","Início","datetime"),f("ends_at","Fim","datetime")]},
  announcements:{label:"Avisos",table:"system_announcements",desc:"Avisos operacionais por público.",create:true,cols:["title","audience","severity","active","starts_at","ends_at"],fields:[f("audience","Público"),f("title","Título"),f("body","Mensagem","textarea"),f("severity","Tipo","select",["info","success","warning","critical"]),f("active","Ativo","checkbox"),f("starts_at","Início","datetime"),f("ends_at","Fim","datetime")]},
  notifications:{label:"Mensagens",table:"notification_templates",key:"key",desc:"Modelos transacionais. Credenciais ficam no servidor.",create:true,cols:["key","channel","audience","title_template","active","updated_at"],fields:[f("key","Chave"),f("channel","Canal","select",["in_app","push","email","whatsapp","sms"]),f("audience","Público"),f("title_template","Título"),f("body_template","Mensagem","textarea"),f("active","Ativo","checkbox")]},
  integrations:{label:"Integrações",table:"integration_registry",key:"key",desc:"Status e parâmetros públicos. Segredos ficam fora do painel.",create:true,cols:["key","label","provider","enabled","environment","status","last_checked_at"],fields:[f("key","Chave"),f("label","Nome"),f("provider","Provedor"),f("enabled","Ativa","checkbox"),f("environment","Ambiente","select",["sandbox","production"]),f("status","Status"),f("public_config","Configuração pública","json"),f("notes","Observações","textarea")]},
  privacy:{label:"LGPD",table:"privacy_requests",desc:"Solicitações de acesso, correção, exclusão e demais direitos.",create:false,del:false,audit:true,cols:["profile_id","request_type","status","details","created_at","resolved_at"],fields:[f("status","Status","select",["open","in_review","completed","rejected"]),f("resolution_notes","Resolução","textarea"),f("resolved_at","Concluído em","datetime")]},
  permissions:{label:"Permissões",table:"admin_permissions",desc:"Defina o que cada administrador pode acessar. Sem registros, um admin mantém acesso total para evitar bloqueio do primeiro administrador.",create:true,del:true,cols:["profile_id","permission","created_at"],fields:[f("profile_id","Administrador UUID"),f("permission","Permissão","select",permissionOptions)]},
  audit:{label:"Auditoria",table:"admin_audit_logs",desc:"Quem alterou o quê, quando e em qual registro.",create:false,del:false,readonly:true,cols:["admin_id","action","entity","entity_id","created_at"]}
};
