import type { DemoOrder, Fair, Product, VendorMetrics } from "./types";

export const categories = [
  "Hortifruti",
  "Carnes",
  "Pescados",
  "Queijos",
  "Padaria",
  "Doces",
  "Comidas prontas",
  "Moda",
  "Artesanato",
  "Casa",
  "Plantas",
  "Presentes",
];

export const fairs: Fair[] = [
  {
    name: "Feira da Torre de TV",
    place: "Plano Piloto",
    address: "Torre de TV, Área Central, Brasília - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente do Gama",
    place: "Gama",
    address: "Área Especial, Quadra 01, Setor Norte, Gama - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Modelo de Sobradinho",
    place: "Sobradinho",
    address: "Quadra Central, Lote M, Sobradinho - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira de Planaltina - Confecções e Utilidades",
    place: "Planaltina",
    address: "Área Pública/RE, Via N/S1, Setor Educacional, Planaltina - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente do Núcleo Bandeirante",
    place: "Núcleo Bandeirante",
    address: "Praça Padre Roque, Projeção 09, 3ª Avenida, Núcleo Bandeirante - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira da Guariroba",
    place: "Ceilândia",
    address: "EQNN 38/40, Área Especial, Ceilândia - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Central de Ceilândia",
    place: "Ceilândia",
    address: "CNM 02, Ceilândia - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente do Guará",
    place: "Guará",
    address: "QE 25, Guará II, Área Especial Cave, Guará - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente do Cruzeiro",
    place: "Cruzeiro",
    address: "SHCES Quadra 609, Lote 03, Cruzeiro - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente de São Sebastião",
    place: "São Sebastião",
    address: "Área Especial 01, Centro de Múltiplas Atividades, São Sebastião - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Shopping Popular da antiga Rodoferroviária",
    place: "Plano Piloto",
    address: "Antiga Rodoferroviária, Brasília - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Shopping Popular do Gama",
    place: "Gama",
    address: "Área Especial, Quadra 01, Setor Norte, Gama - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Shopping Popular Taguatinga Sul",
    place: "Taguatinga",
    address: "QS 03/04, Rua 320, Área Especial, Taguatinga - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente M Norte",
    place: "Taguatinga",
    address: "QNM 38/40, Área Especial, Taguatinga Norte - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira dos Importados Taguatinga Centro",
    place: "Taguatinga",
    address: "Área Especial 07, Feira dos Importados de Taguatinga, Taguatinga - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente da QNJ/QNL",
    place: "Taguatinga",
    address: "Área Especial 01, QNJ/QNL, Taguatinga Norte - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Central de Brazlândia",
    place: "Brazlândia",
    address: "Setor Norte, SCDN Lote O, Brazlândia - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira do Produtor Rural",
    place: "Planaltina",
    address: "Via N/S, Setor Educacional, Planaltina - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira de Hortifrutigranjeiros",
    place: "Planaltina",
    address: "E/Q 3/4, Setor Residencial Leste, Planaltina - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente do Paranoá",
    place: "Paranoá",
    address: "Quadra 26, Conjunto G, Lote 03, Paranoá - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira do Produtor",
    place: "Ceilândia",
    address: "QNP 01, Área Especial I, Setor P Norte, Ceilândia - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira do P Sul",
    place: "Ceilândia",
    address: "EQNP 26/30, Área Especial, Ceilândia - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira do P Norte",
    place: "Ceilândia",
    address: "QNN 37, Área Especial, Ceilândia - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Shopping Popular de Ceilândia",
    place: "Ceilândia",
    address: "QNN 11, Área Especial, Ceilândia - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira do Setor O",
    place: "Ceilândia",
    address: "EQNO 10/12, Área Especial, Ceilândia - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente da QN 202",
    place: "Samambaia",
    address: "QN 202, Área Especial 01, Samambaia - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente da QN 210",
    place: "Samambaia",
    address: "QN 210, Samambaia - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente de Santa Maria",
    place: "Santa Maria",
    address: "QC 01, Conjunto C, Lote 44, Santa Maria - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente do Recanto das Emas",
    place: "Recanto das Emas",
    address: "SEUB Centro, Quadra 305/311, Avenida Recanto das Emas, Recanto das Emas - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira do Riacho Fundo I",
    place: "Riacho Fundo I",
    address: "AC 03, Lotes 02/04, Riacho Fundo - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente da Candangolândia",
    place: "Candangolândia",
    address: "Quadra 01, Lote 04, Candangolândia - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente Riacho Fundo II",
    place: "Riacho Fundo II",
    address: "QN 10, Conjunto 05, Lotes 03/06, Área Especial, Riacho Fundo II - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente da Cidade Estrutural",
    place: "SCIA/Estrutural",
    address: "Setor Central, Área Especial 04, Vila Estrutural, SCIA/Estrutural - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente de Sobradinho II",
    place: "Sobradinho II",
    address: "AR 5 - 06/08, Sobradinho II - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Permanente do Jardim Botânico",
    place: "Jardim Botânico",
    address: "Condomínio San Diego, DF-001, Galpão Feira, Jardim Botânico - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira da Cultura, Arte e Beleza do SIA - FECAB",
    place: "SIA",
    address: "SIA Trecho 07, Brasília - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira do Produtor em Vicente Pires",
    place: "Vicente Pires",
    address: "SHVP Rua 04 A, Vicente Pires - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira da Fercal",
    place: "Fercal",
    address: "DF-150, km 12, Rua 02, Lote 60, Lojas 04/06, Bairro Engenho Velho, Fercal - DF",
    status: "Horário a confirmar",
    source: "official",
  },
  {
    name: "Feira Central de Brasília",
    place: "Plano Piloto",
    active: false,
    status: "Cadastro demonstrativo",
    source: "demo",
    feirantes: 60,
    rating: 4.7,
    reviewCount: 718,
    deliveryMinutes: [45, 65],
    deliveryFee: 13.9,
    lat: -15.793,
    lng: -47.882,
  },
  {
    name: "Feira Permanente de Planaltina",
    place: "Planaltina",
    active: false,
    status: "Cadastro demonstrativo",
    source: "demo",
    feirantes: 42,
    rating: 4.7,
    reviewCount: 414,
    deliveryMinutes: [27, 42],
    deliveryFee: 7.9,
    lat: -15.617,
    lng: -47.65,
  },
];

export const vendorMetrics: Record<string, VendorMetrics> = {
  "Sítio da Vó": { rating: 4.9, reviewCount: 300, deliveryMinutes: [35, 50], deliveryFee: 7.9 },
  "Queijaria do Cerrado": { rating: 4.8, reviewCount: 184, deliveryMinutes: [38, 55], deliveryFee: 8.9 },
  "Delícias da Feira": { rating: 4.7, reviewCount: 126, deliveryMinutes: [45, 60], deliveryFee: 10.9 },
  "Forno da Praça": { rating: 4.8, reviewCount: 436, deliveryMinutes: [40, 55], deliveryFee: 8.9 },
  "Verde Cerrado": { rating: 4.7, reviewCount: 212, deliveryMinutes: [55, 75], deliveryFee: 13.9 },
  "Mãos do DF": { rating: 4.9, reviewCount: 159, deliveryMinutes: [50, 70], deliveryFee: 12.9 },
  "Apiário Cerrado": { rating: 4.8, reviewCount: 98, deliveryMinutes: [45, 62], deliveryFee: 9.9 },
  "Pastelaria da Feira": { rating: 4.8, reviewCount: 332, deliveryMinutes: [25, 40], deliveryFee: 6.9 },
  "Horta Planaltina": { rating: 4.7, reviewCount: 221, deliveryMinutes: [30, 45], deliveryFee: 7.9 },
  "Sabores do Guará": { rating: 4.8, reviewCount: 176, deliveryMinutes: [50, 70], deliveryFee: 14.9 },
  "Doces do Cruzeiro": { rating: 4.7, reviewCount: 143, deliveryMinutes: [52, 72], deliveryFee: 15.9 },
  "Café Bandeirante": { rating: 4.8, reviewCount: 267, deliveryMinutes: [55, 75], deliveryFee: 16.9 },
  "Raízes de Sobradinho": { rating: 4.7, reviewCount: 203, deliveryMinutes: [42, 60], deliveryFee: 11.9 },
  "Mãos de Ceilândia": { rating: 4.8, reviewCount: 188, deliveryMinutes: [60, 85], deliveryFee: 18.9 },
  "Jardim de Vicente": { rating: 4.7, reviewCount: 116, deliveryMinutes: [58, 82], deliveryFee: 17.9 },
  "Forno de São Sebastião": { rating: 4.6, reviewCount: 92, deliveryMinutes: [62, 90], deliveryFee: 19.9 },
  "Pescados Planaltina": { rating: 4.7, reviewCount: 274, deliveryMinutes: [28, 45], deliveryFee: 8.9 },
};

export const products: Product[] = [
  {
    id: 1,
    name: "Cesta de frutas",
    feirante: "Sítio da Vó",
    fair: "Feira do Produtor Rural",
    price: 24.9,
    category: "Hortifruti",
    emoji: "🍎",
    stock: 30,
    unit: "cesta",
    weightKg: 4,
    volume: "medio",
    featured: true,
  },
  {
    id: 2,
    name: "Queijo artesanal",
    feirante: "Queijaria do Cerrado",
    fair: "Feira do Produtor Rural",
    price: 32,
    category: "Queijos",
    emoji: "🧀",
    stock: 18,
    unit: "peça",
    weightKg: 0.8,
    volume: "leve",
    featured: true,
  },
  {
    id: 3,
    name: "Bolo de milho",
    feirante: "Delícias da Feira",
    fair: "Feira Central de Brasília",
    price: 18,
    category: "Doces",
    emoji: "🌽",
    stock: 12,
    unit: "unidade",
    weightKg: 0.7,
    volume: "leve",
  },
  {
    id: 4,
    name: "Cesta de pães",
    feirante: "Forno da Praça",
    fair: "Feira Central de Brasília",
    price: 21.5,
    category: "Padaria",
    emoji: "🥖",
    stock: 25,
    unit: "cesta",
    weightKg: 2.2,
    volume: "medio",
    featured: true,
  },
  {
    id: 5,
    name: "Planta ornamental",
    feirante: "Verde Cerrado",
    fair: "Feira da Torre de TV",
    price: 28,
    category: "Plantas",
    emoji: "🪴",
    stock: 9,
    unit: "vaso",
    weightKg: 1.5,
    volume: "medio",
  },
  {
    id: 6,
    name: "Bolsa artesanal",
    feirante: "Mãos do DF",
    fair: "Feira da Torre de TV",
    price: 69.9,
    category: "Artesanato",
    emoji: "👜",
    stock: 7,
    unit: "unidade",
    weightKg: 0.6,
    volume: "leve",
    featured: true,
  },
  {
    id: 7,
    name: "Mel artesanal",
    feirante: "Apiário Cerrado",
    fair: "Feira Central de Brasília",
    price: 28,
    category: "Doces",
    emoji: "🍯",
    stock: 15,
    unit: "pote",
    weightKg: 0.5,
    volume: "leve",
  },
  {
    id: 8,
    name: "Pastel de carne",
    feirante: "Pastelaria da Feira",
    fair: "Feira do Produtor Rural",
    price: 9.5,
    category: "Comidas prontas",
    emoji: "🥟",
    stock: 40,
    unit: "unidade",
    weightKg: 0.15,
    volume: "leve",
  },
  {
    id: 9,
    name: "Tomate orgânico",
    feirante: "Sítio da Vó",
    fair: "Feira do Produtor Rural",
    price: 8.9,
    category: "Hortifruti",
    emoji: "🍅",
    stock: 22,
    unit: "kg",
    weightKg: 1,
    volume: "leve",
  },
  {
    id: 10,
    name: "Flores do campo",
    feirante: "Verde Cerrado",
    fair: "Feira da Torre de TV",
    price: 19.9,
    category: "Presentes",
    emoji: "💐",
    stock: 11,
    unit: "buquê",
    weightKg: 0.35,
    volume: "leve",
  },
  {
    id: 11,
    name: "Verduras da estação",
    feirante: "Horta Planaltina",
    fair: "Feira de Hortifrutigranjeiros",
    price: 12.9,
    category: "Hortifruti",
    emoji: "🥬",
    stock: 28,
    unit: "maço",
    weightKg: 0.25,
    volume: "leve",
  },
  {
    id: 12,
    name: "Kit temperos do cerrado",
    feirante: "Sabores do Guará",
    fair: "Feira Permanente do Guará",
    price: 18.5,
    category: "Casa",
    emoji: "🌿",
    stock: 16,
    unit: "kit",
    weightKg: 0.4,
    volume: "leve",
  },
  {
    id: 13,
    name: "Doce de leite artesanal",
    feirante: "Doces do Cruzeiro",
    fair: "Feira Permanente do Cruzeiro",
    price: 22,
    category: "Doces",
    emoji: "🍮",
    stock: 14,
    unit: "pote",
    weightKg: 0.65,
    volume: "leve",
  },
  {
    id: 14,
    name: "Café torrado no DF",
    feirante: "Café Bandeirante",
    fair: "Feira Permanente do Núcleo Bandeirante",
    price: 29.9,
    category: "Casa",
    emoji: "☕",
    stock: 21,
    unit: "pacote",
    weightKg: 0.5,
    volume: "leve",
  },
  {
    id: 15,
    name: "Cesta do produtor",
    feirante: "Raízes de Sobradinho",
    fair: "Feira Permanente de Sobradinho II",
    price: 34.9,
    category: "Hortifruti",
    emoji: "🥕",
    stock: 20,
    unit: "cesta",
    weightKg: 6,
    volume: "pesado",
    featured: true,
  },
  {
    id: 16,
    name: "Jogo de panos bordados",
    feirante: "Mãos de Ceilândia",
    fair: "Feira do Produtor",
    price: 39.9,
    category: "Artesanato",
    emoji: "🪡",
    stock: 8,
    unit: "jogo",
    weightKg: 0.7,
    volume: "leve",
  },
  {
    id: 17,
    name: "Vaso de suculentas",
    feirante: "Jardim de Vicente",
    fair: "Feira do Produtor em Vicente Pires",
    price: 24,
    category: "Plantas",
    emoji: "🌵",
    stock: 13,
    unit: "vaso",
    weightKg: 1.2,
    volume: "medio",
  },
  {
    id: 18,
    name: "Biscoito caseiro",
    feirante: "Forno de São Sebastião",
    fair: "Feira Permanente de São Sebastião",
    price: 16.9,
    category: "Padaria",
    emoji: "🍪",
    stock: 25,
    unit: "pacote",
    weightKg: 0.45,
    volume: "leve",
  },
  {
    id: 19,
    name: "Filé de tilápia fresco",
    feirante: "Pescados Planaltina",
    fair: "Feira Permanente de Planaltina",
    price: 42.9,
    category: "Pescados",
    emoji: "🐟",
    stock: 18,
    unit: "kg",
    weightKg: 1,
    volume: "leve",
    featured: true,
  },
  {
    id: 20,
    name: "Camarão selecionado",
    feirante: "Pescados Planaltina",
    fair: "Feira Permanente de Planaltina",
    price: 58,
    category: "Pescados",
    emoji: "🦐",
    stock: 10,
    unit: "kg",
    weightKg: 1,
    volume: "leve",
  },
];

export const initialOrders: DemoOrder[] = [
  { id: "FE-1024", date: "20/09/2026", status: "Em rota", value: 58.7 },
  { id: "FE-1019", date: "19/09/2026", status: "Entregue", value: 42.9 },
];
