import type { DemoOrder, Fair, Product } from "./types";

export const categories = [
  "Hortifruti",
  "Carnes",
  "Queijos",
  "Padaria",
  "Doces",
  "Comidas prontas",
  "Moda",
  "Artesanato",
  "Casa",
  "Plantas",
  "Presentes",
];

export const fairs: Fair[] = [
  {
    name: "Feira do Produtor",
    place: "Planaltina",
    status: "Seg e qui · 19h–2h",
    feirantes: 48,
    lat: -15.621,
    lng: -47.657,
  },
  {
    name: "Feira de Hortifrutigranjeiros",
    place: "Planaltina",
    status: "Ter–dom · 7h–18h",
    feirantes: 36,
    lat: -15.617,
    lng: -47.651,
  },
  {
    name: "Feira Central de Brasília",
    place: "Plano Piloto",
    status: "Consulte o horário",
    feirantes: 60,
    lat: -15.793,
    lng: -47.882,
  },
  {
    name: "Feira Permanente do Guará",
    place: "Guará",
    status: "Ter–dom · 8h–18h",
    feirantes: 50,
    lat: -15.829,
    lng: -47.976,
  },
  {
    name: "Feira Permanente do Cruzeiro",
    place: "Cruzeiro",
    status: "Ter–dom · 8h–18h",
    feirantes: 40,
    lat: -15.792,
    lng: -47.938,
  },
  {
    name: "Feira do Núcleo Bandeirante",
    place: "Núcleo Bandeirante",
    status: "Ter–dom · 8h–18h",
    feirantes: 45,
    lat: -15.871,
    lng: -47.969,
  },
  {
    name: "Feira de Sobradinho II",
    place: "Sobradinho II",
    status: "Qua–dom · 8h–18h",
    feirantes: 35,
    lat: -15.652,
    lng: -47.788,
  },
  {
    name: "Feira do Produtor de Ceilândia",
    place: "Ceilândia",
    status: "Qua–dom · 7h–18h",
    feirantes: 55,
    lat: -15.82,
    lng: -48.11,
  },
  {
    name: "Feira do Produtor de Vicente Pires",
    place: "Vicente Pires",
    status: "Qui–dom · 8h–18h",
    feirantes: 45,
    lat: -15.8,
    lng: -48.02,
  },
  {
    name: "Feira de São Sebastião",
    place: "São Sebastião",
    status: "Ter–dom · 8h–18h",
    feirantes: 30,
    lat: -15.9,
    lng: -47.77,
  },
  {
    name: "Feira de Artesanato da Torre",
    place: "Plano Piloto",
    status: "Sáb e dom · 9h–18h",
    feirantes: 70,
    lat: -15.79,
    lng: -47.894,
  },
];

export const products: Product[] = [
  {
    id: 1,
    name: "Cesta de frutas",
    feirante: "Sítio da Vó",
    fair: "Feira do Produtor",
    price: 24.9,
    category: "Hortifruti",
    emoji: "🍎",
    stock: 30,
    unit: "cesta",
    featured: true,
  },
  {
    id: 2,
    name: "Queijo artesanal",
    feirante: "Queijaria do Cerrado",
    fair: "Feira do Produtor",
    price: 32,
    category: "Queijos",
    emoji: "🧀",
    stock: 18,
    unit: "peça",
    featured: true,
  },
  {
    id: 3,
    name: "Bolo de milho",
    feirante: "Delícias da Feira",
    fair: "Feira Central de Brasília",
    price: 18,
    category: "Doces",
    emoji: "🌽",
    stock: 12,
    unit: "unidade",
  },
  {
    id: 4,
    name: "Cesta de pães",
    feirante: "Forno da Praça",
    fair: "Feira Central de Brasília",
    price: 21.5,
    category: "Padaria",
    emoji: "🥖",
    stock: 25,
    unit: "cesta",
    featured: true,
  },
  {
    id: 5,
    name: "Planta ornamental",
    feirante: "Verde Cerrado",
    fair: "Feira de Artesanato da Torre",
    price: 28,
    category: "Plantas",
    emoji: "🪴",
    stock: 9,
    unit: "vaso",
  },
  {
    id: 6,
    name: "Bolsa artesanal",
    feirante: "Mãos do DF",
    fair: "Feira de Artesanato da Torre",
    price: 69.9,
    category: "Artesanato",
    emoji: "👜",
    stock: 7,
    unit: "unidade",
    featured: true,
  },
  {
    id: 7,
    name: "Mel artesanal",
    feirante: "Apiário Cerrado",
    fair: "Feira Central de Brasília",
    price: 28,
    category: "Doces",
    emoji: "🍯",
    stock: 15,
    unit: "pote",
  },
  {
    id: 8,
    name: "Pastel de carne",
    feirante: "Pastelaria da Feira",
    fair: "Feira do Produtor",
    price: 9.5,
    category: "Comidas prontas",
    emoji: "🥟",
    stock: 40,
    unit: "unidade",
  },
  {
    id: 9,
    name: "Tomate orgânico",
    feirante: "Sítio da Vó",
    fair: "Feira do Produtor",
    price: 8.9,
    category: "Hortifruti",
    emoji: "🍅",
    stock: 22,
    unit: "kg",
  },
  {
    id: 10,
    name: "Flores do campo",
    feirante: "Verde Cerrado",
    fair: "Feira de Artesanato da Torre",
    price: 19.9,
    category: "Presentes",
    emoji: "💐",
    stock: 11,
    unit: "buquê",
  },
  {
    id: 11,
    name: "Verduras da estação",
    feirante: "Horta Planaltina",
    fair: "Feira de Hortifrutigranjeiros",
    price: 12.9,
    category: "Hortifruti",
    emoji: "🥬",
    stock: 28,
    unit: "maço",
  },
  {
    id: 12,
    name: "Kit temperos do cerrado",
    feirante: "Sabores do Guará",
    fair: "Feira Permanente do Guará",
    price: 18.5,
    category: "Casa",
    emoji: "🌿",
    stock: 16,
    unit: "kit",
  },
  {
    id: 13,
    name: "Doce de leite artesanal",
    feirante: "Doces do Cruzeiro",
    fair: "Feira Permanente do Cruzeiro",
    price: 22,
    category: "Doces",
    emoji: "🍮",
    stock: 14,
    unit: "pote",
  },
  {
    id: 14,
    name: "Café torrado no DF",
    feirante: "Café Bandeirante",
    fair: "Feira do Núcleo Bandeirante",
    price: 29.9,
    category: "Casa",
    emoji: "☕",
    stock: 21,
    unit: "pacote",
  },
  {
    id: 15,
    name: "Cesta do produtor",
    feirante: "Raízes de Sobradinho",
    fair: "Feira de Sobradinho II",
    price: 34.9,
    category: "Hortifruti",
    emoji: "🥕",
    stock: 20,
    unit: "cesta",
    featured: true,
  },
  {
    id: 16,
    name: "Jogo de panos bordados",
    feirante: "Mãos de Ceilândia",
    fair: "Feira do Produtor de Ceilândia",
    price: 39.9,
    category: "Artesanato",
    emoji: "🪡",
    stock: 8,
    unit: "jogo",
  },
  {
    id: 17,
    name: "Vaso de suculentas",
    feirante: "Jardim de Vicente",
    fair: "Feira do Produtor de Vicente Pires",
    price: 24,
    category: "Plantas",
    emoji: "🌵",
    stock: 13,
    unit: "vaso",
  },
  {
    id: 18,
    name: "Biscoito caseiro",
    feirante: "Forno de São Sebastião",
    fair: "Feira de São Sebastião",
    price: 16.9,
    category: "Padaria",
    emoji: "🍪",
    stock: 25,
    unit: "pacote",
  },
];

export const initialOrders: DemoOrder[] = [
  { id: "FE-1024", date: "20/09/2026", status: "Em rota", value: 58.7 },
  { id: "FE-1019", date: "19/09/2026", status: "Entregue", value: 42.9 },
];
